In [53]:
from openpyxl import load_workbook
import pandas as pd

from sklearn import preprocessing as pre #untuk proses preprocessing
from sklearn.svm import SVR        #untuk import metode SVR (forecasting)
from sklearn.metrics import mean_squared_error   #library untuk metode pengujian 

In [54]:
wb = load_workbook(filename='Data Alumni.xlsx')
sheet = wb['Sheet1']
data = pd.DataFrame (sheet.values)
data

0         1                     2   \
0   DATA ALUMNI      None                  None   
1          None      None                  None   
2            No       Nim                 Nama    
3          None      None                  None   
4             1   9018263      Puguh Drajat E.P   
5             2  12022030  Arsyad Cahya Subrata   
6             3  12020021          Yesi Novela    
7             4   9018269       Pandu Herwijaya   
8             5   9018109        Anjar Prasetyo   
9             6   9020026   Moh. Dadi Kurniawan   
10            7  12018060        Martin Sarlina   
11            8  11018022      Yan Adhi Permadi   
12            9   9018212       Achicha Wahyuni   
13           10   9018301   Yayan Tisna Permadi   
14           11  12022020        Muh. Rama dhai   
15           12  12022038           Nurwahyuddi   
16           13  12019039          Agus Purnomo   
17           14  11018111  M. Akhwan Zulfayandi   
18           15   9018135   Yunita Tri Hernawai   
19           16  12018161     Pratama Setya Aji   

                                  3                        4   \
0                               None                     None   
1                               None                     None   
2             Tempat & tanggal lahir     Fakultas/Ketrampilan   
3                               None                     None   
4         Purworejo, 4 November 1989  FTI / Teknik Iformatika   
5               Bantul, 21 juni 1994     FTI / Teknik Elektro   
6          Tempilang, 1 januari 1995                      FTI   
7          Lampung, 19 Desember 1990   FTI/ Teknik Infomatika   
8         Gunungkidul, 27 April 1991  FTI /Teknik Informatika   
9          Savanajaya, 27 Maret 1992             FTI / Futsal   
10              Lepak, 23 Maret 1994                      FTI   
11              Jepara, 22 juni 1993                      FTI   
12           Yogyakarta, 3 juni 1991          FTI/ Web Design   
13      Purbalingga, 08 Oktober 1991   FTI/ Teknik Inormatika   
14          Pekanbaru, 29 Maret 1992     FTI / Teknik Elektro   
15  Dili, timor-timur/ 13 April 1995     FTI / Teknik Elektro   
16            Klaten, 2 Agustus 1992     FTI/ Teknik Industri   
17          Teros, 12 September 1992  FTI/ Teknik Informatika   
18            Magelang, 20 Juni 1991  FTI/ Teknik Informatika   
19         Sleman, 20 September 1994                      FTI   

                                                   5            6   \
0                                                None         None   
1                                                None         None   
2                                              Alamat  Tahun Masuk   
3                                                None         None   
4                                 Tangerang Rt. 01/ 0         2009   
5    Karangpule Rt.01 , Tirtonirmolo , Kasihan Bantul         2012   
6                                                None         2012   
7                         Tamantirto, Kasihan ,Bantul         2009   
8                             Umbulharjo , Yogyakarta         2009   
9                   Saren Rt. 02 Rw. 01 Caturtunggal          2009   
10                                                NTB         2012   
11                                       Umbulharjo V         2011   
12                    Noyokerten, Sendangirto, Berbah         2009   
13                       Tajug, Rt.04/ 05 Purbalingga         2009   
14     Karongan Rt/Rw. 04/11 Jogotirto, Berbah Sleman         2012   
15                 Juru Gentong J V/407 C Banguntapan         2012   
16                      Dukuh Glagahwangi, Polanharjo         2012   
17  Jl. Peumnas gg. Indragiri Blok B/24, Condongcatur         2011   
18                                           Magelang         2009   
19           Jl. Affandi gg.Kamboja CTX.19 Yogyakarta         2012   

             7                 8                         9   ...      14  \
0          None             

In [55]:
d = data[4:20][[12,6,7]]

d.columns = ['IPK','TAHUN MASUK','TAHUN LULUS']
d = d.dropna(axis=0, how='any')
d

IPK TAHUN MASUK TAHUN LULUS
4   2,13        2009        2016
7   2,75        2009        2016
9   3,24        2009        2016
10  3,27        2012        2016
11  3,20        2011        2016
12  3,24        2009        2016
13  3,06        2009        2016
14  3.47        2012        2016
15  3,62        2012        2016
16  3,32        2012        2016
17  3,14        2011        2016
18  2,99        2009        2016
19  3,60        2012        2016

In [56]:
p = d.dropna() #cleaning data
p

IPK TAHUN MASUK TAHUN LULUS
4   2,13        2009        2016
7   2,75        2009        2016
9   3,24        2009        2016
10  3,27        2012        2016
11  3,20        2011        2016
12  3,24        2009        2016
13  3,06        2009        2016
14  3.47        2012        2016
15  3,62        2012        2016
16  3,32        2012        2016
17  3,14        2011        2016
18  2,99        2009        2016
19  3,60        2012        2016

In [57]:
for index, row in p.iterrows():
    p.ix[index, 'MASA STUDI'] = row['TAHUN LULUS'] - row['TAHUN MASUK']

p['IPK'] = p['IPK'].apply(str)
p['IPK'] = p['IPK'].str.replace(',','.').apply(float)

print(p.dtypes)

IPK            float64
TAHUN MASUK     object
TAHUN LULUS     object
MASA STUDI     float64
dtype: object


C:\Users\User\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [58]:
training = p.reset_index(drop=True)
training

IPK TAHUN MASUK TAHUN LULUS  MASA STUDI
0   2.13        2009        2016         7.0
1   2.75        2009        2016         7.0
2   3.24        2009        2016         7.0
3   3.27        2012        2016         4.0
4   3.20        2011        2016         5.0
5   3.24        2009        2016         7.0
6   3.06        2009        2016         7.0
7   3.47        2012        2016         4.0
8   3.62        2012        2016         4.0
9   3.32        2012        2016         4.0
10  3.14        2011        2016         5.0
11  2.99        2009        2016         7.0
12  3.60        2012        2016         4.0

In [59]:
label = training['MASA STUDI'].values
label

array([7., 7., 7., 4., 5., 7., 7., 4., 4., 4., 5., 7., 4.])

In [60]:
feature = training[['IPK']].values
feature

array([[2.13],
       [2.75],
       [3.24],
       [3.27],
       [3.2 ],
       [3.24],
       [3.06],
       [3.47],
       [3.62],
       [3.32],
       [3.14],
       [2.99],
       [3.6 ]])

In [2]:
SVR_model = SVR(kernel='precomputed',ted().fit(feature)
x = scaler.transform(feature)
x

NameError: name 'pre' is not defined

In [62]:
import numpy as np
from sklearn import svm
X = np.array([[0, 0], [1, 1]])
y = [0, 1]
clf = svm.SVC(kernel='precomputed')
# linear kernel computation
gram = np.dot(X, X.T)
clf.fit(gram, y) 




SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto',
  kernel='precomputed', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [63]:
testing = training.sample(n=13)
testing

IPK TAHUN MASUK TAHUN LULUS  MASA STUDI
3   3.27        2012        2016         4.0
0   2.13        2009        2016         7.0
11  2.99        2009        2016         7.0
5   3.24        2009        2016         7.0
8   3.62        2012        2016         4.0
7   3.47        2012        2016         4.0
4   3.20        2011        2016         5.0
12  3.60        2012        2016         4.0
10  3.14        2011        2016         5.0
2   3.24        2009        2016         7.0
6   3.06        2009        2016         7.0
1   2.75        2009        2016         7.0
9   3.32        2012        2016         4.0

In [64]:
feature_test = testing[list(['IPK'])].values
feature_test

array([[3.27],
       [2.13],
       [2.99],
       [3.24],
       [3.62],
       [3.47],
       [3.2 ],
       [3.6 ],
       [3.14],
       [3.24],
       [3.06],
       [2.75],
       [3.32]])

In [1]:
scaler_test = pre.StandardScaler().fit(feature_test)
test = scaler_test.transform(feature_test)
test

NameError: name 'pre' is not defined

In [66]:
y_pred = SVR_model.predict(test)
y_pred

array([5.09999993, 5.10005405, 5.10000023, 5.09999997, 5.09999501,
       5.09999846, 5.1       , 5.09999563, 5.1       , 5.09999997,
       5.10000005, 5.10000335, 5.09999978])

# pengujian MSE

In [67]:
y_true = testing['MASA STUDI'].values
y_true

array([4., 7., 7., 7., 4., 4., 5., 4., 5., 7., 7., 7., 4.])

In [68]:
mean_squared_error(y_true,y_pred)


2.1330581855780717